export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
  body: document?.querySelector('.page__body'),
  headerMain: document?.querySelector('.header-main'),
  hero: document?.querySelector('.hero'),
  cartClose: document?.querySelectorAll('.cart-content__close'),
  cartOverlay: document?.querySelector('.cart-overlay'),
  cartContent: document?.querySelector('.cart-content'),
  cartIcon: document?.querySelectorAll('.cart-icon'),
  cartProdictList: document?.querySelector('.cart-content__list'),
  cartPageList: document?.querySelector('.order__list'),
  basket: document?.querySelectorAll('.basket'),
  addCart: document?.querySelector('.card-info__cart'),
  basketQuantity: document?.querySelectorAll('.basket__quantity'),
  fullPrice: document?.querySelector('.cart-content__fullprice'),
  btnsAddCart: document?.querySelectorAll('.product-slider__to-cart'),
  // productPrice: document?.querySelectorAll('.cart-product__price'),
}
